apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: dnNoWw==  # Base64 encoded value of 'vishnu'
  MONGO_INITDB_ROOT_PASSWORD: cXdlcmFzZGZ=  # Base64 encoded value of 'qwerasdf'
